apiVersion v1
kind Service
metadata
  name common-service
  labels
    app common-app
spec
  type NodePort
  selector
    app common-app
  ports
    - name http
      nodePort 30001 
      port 9090
      targetPort 9090
      protocol TCP